### ISSUE TITLE
How to update module item every time an action bar message is received?

### ISSUE THREAD

**Issue by ghost** [5zig/The-5zig-API#3] opened 2017-03-19 12:33 UTC
From the example plugin provided and the source code I can't figure out how to do this.

**Comment by 5zig** [comment] 2017-03-19 17:24
First, you need to [register a server instance](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/MainTest.java#L32), then you need to [register a server listener](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/TestServerInstance.java#L9), provide a [data-handler class](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/TestServerGameListener.java#L11) and [override the onActionBar method](https://github.com/5zig/The-5zig-API/blob/master/src/eu/the5zig/mod/server/AbstractGameListener.java#L133). You can then update the variables you want by referencing the `gameMode` parameter.
Now [register a module item](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/MainTest.java#L35), [provide your created date class to the super constructor](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/TestServerGameItem.java#L27) and [implement the get value method](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/TestServerGameItem.java#L32).

**Comment by ghost** [comment] 2017-03-20 07:45
Do I need to make a `ServerListener` or a `ServerGameListener` class at

>then you need to [register a server listener](https://github.com/5zig/The-5zig-API/blob/master/test/eu/the5zig/api/test/TestServerInstance.java#L9)

And what methods would I need to specify?

**Comment by ghost** [comment] 2017-03-20 13:18
> You can then update the variables you want by referencing the `gameMode` parameter.

Sorry to be a pain, but do you have an example of how I can do this?

What if I want to make the `ModuleItem` simply render the most recent action bar message?

**Comment by 5zig** [comment] 2017-03-20 15:45
I've added an example plugin to [examples/basic2](https://github.com/5zig/The-5zig-API/tree/master/examples/basic2) which should help you.

**Comment by ghost** [comment] 2017-03-20 21:09
Wow, thank you so much for putting all the work into creating that helpful example for me!

I am having a problem though, I can't see the module in the HUD, even though I can locate it in Options>5zig>Display

**Comment by 5zig** [comment] 2017-03-22 18:17
Are you sure that you are playing on the server you specified? Also, you need to add the created item in the Customize Display GUI of the mod.

**Comment by ghost** [comment] 2017-03-23 07:47
> are you playing on the server you specified? 

What do you mean? How can I just make it run on every server?

**Comment by 5zig** [comment] 2017-03-23 10:34
Call `return true` [here](https://github.com/5zig/The-5zig-API/blob/master/examples/basic2/eu/the5zig/api/test/MyServerInstance.java#L28).

**Comment by ghost** [comment] 2017-03-23 11:27
I already am. In fact, my file is identical to that one:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.server.ServerInstance;

public class ServerInstanceHandler extends ServerInstance {
  @Override
  public void registerListeners() {
    // Register a listener class
    getGameListener().registerListener(new MyActionBarListener());
  }

  @Override
  public String getName() {
    return "localhost";
  }

  @Override
  public String getConfigName() {
    return "localhost";
  }

  @Override
  public boolean handleServer(String host, int port) {
    return true;
  }
}

```

**Comment by ghost** [comment] 2017-03-23 11:28
Then I have my `MyActionBarListener`:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.server.AbstractGameListener;
import eu.the5zig.util.minecraft.ChatColor;

public class MyActionBarListener extends AbstractGameListener<MyServer.MainServer> {
  @Override
  public Class<MyServer.MainServer> getGameMode() {
    return MyServer.MainServer.class;
  }

  @Override
  public boolean matchLobby(String lobby) {
    return true;
  }

  @Override
  public boolean onActionBar(MyServer.MainServer gameMode, String message) {
    gameMode.lastActionBarMessage = ChatColor.stripColor(message);
    return false;
  }
}

```

**Comment by ghost** [comment] 2017-03-23 11:29
and my `MyServer`:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.server.GameMode;

public class MyServer {

  public static class MainServer extends GameMode {

    public String lastActionBarMessage;

    @Override
    public String getName() {
      return "Server";
    }

  }
}

```

**Comment by ghost** [comment] 2017-03-23 11:32
`MyModuleItem`:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.modules.GameModeItem;

public class MyModuleItem extends GameModeItem<MyServer.MainServer> {
  public MyModuleItem() {
    super(MyServer.MainServer.class);
  }

  @Override
  protected Object getValue(boolean dummy) {
    if (dummy) {
      return "Example Action Bar Message";
    } else {
      return getGameMode().lastActionBarMessage;
    }
  }

  @Override
  public String getName() {
    return "AddOns";
  }
}
```

`Main`

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.The5zigAPI;
import eu.the5zig.mod.event.EventHandler;
import eu.the5zig.mod.event.LoadEvent;
import eu.the5zig.mod.modules.Category;
import eu.the5zig.mod.plugin.Plugin;

@Plugin(name = "AddOns", version = "1.0")
public class Main {
  @EventHandler(priority = EventHandler.Priority.LOW)
  public void onLoad(LoadEvent event) {
    The5zigAPI.getAPI().registerServerInstance(this, ServerInstanceHandler.class);
    The5zigAPI.getAPI().registerModuleItem(this, "AddOns", MyModuleItem.class, Category.OTHER);
  }
}

```

**Comment by theonlygusti** [comment] 2017-03-25 18:13
Hey, just wondering when you'll be able to help on this.

**Comment by ghost** [comment] 2017-03-26 22:19
I guess you've been pretty busy for the last four days, I definitely have! Too many deadlines...

Anyway, I was wondering if you could give me a guess as to when you'll get around to taking a look at this?

All your help so far has been absolutely brilliant so don't feel that you have to do anything soon (I know I just dumped a huge load of code here, me myself having no idea what to do xD) I'd just like to know when you'd next be able to help me with this :)

**Comment by 5zig** [comment] 2017-03-29 10:01
I'm sorry for the late response, but I've now finally figured out how to solve your problem.

The issue is the following: the `MyActionBarListener` doesn't get activated because you have to call `switchLobby` at least once. To do this, you need to create another Listener class, register it and return `null` in `getGameMode()`. Now override the `onServerJoin` method and call `getGameListener().switchLobby("Lobby");`
The issue was also present in the example plugin, so I've just updated it.

Let me know if that resolved your issue. Sorry again for the late reply, I didn't have a lot time during the past week.

**Comment by 5zig** [comment] 2017-03-29 10:04
I realize that the Api may seem a little bit too complicated, especially if you just want to support a single server, but it is really powerful when you want to support large server networks with many different child servers and lobbies (like for example the hypixel.net server). I might add a simplified concept for vanilla servers sometime in the future though.

**Comment by ghost** [comment] 2017-03-29 15:15
That hasn't resolved the issue, it's still not displaying.

I added this file:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.server.AbstractGameListener;

public class MyLobbyListener extends AbstractGameListener<MyServer.MainServer> {
  @Override
  public Class<MyServer.MainServer> getGameMode() {
    return null;
  }

  @Override
  public boolean matchLobby(String lobby) {
    return false;
  }

  @Override
  public void onServerJoin() {
    getGameListener().switchLobby("Lobby");
  }
}

```

**Comment by 5zig** [comment] 2017-03-29 15:17
Have you registered it, too?

**Comment by ghost** [comment] 2017-03-29 15:17
> support large server networks with many different child servers and lobbies

Reading this I tried to use it on mineplex, and it still wasn't working. Are there actually ways for a module item to display only on one type of lobby? E.g. `SG-1`?

**Comment by ghost** [comment] 2017-03-29 15:17
Oh I don't think I registered it. Where does that happen? (And by the way thanks for your awesomely fast response XD)

**Comment by 5zig** [comment] 2017-03-29 15:17
Same as with the `MyActionBarListener` class.

**Comment by ghost** [comment] 2017-03-29 15:27
It still doesn't work, and I've registered it now.

Here's my `MyServerInstance`:

```java
package io.github.theonlygusti.fivezigaddons;

import eu.the5zig.mod.server.ServerInstance;

public class MyServerInstance extends ServerInstance {
  @Override
  public void registerListeners() {
    // Register a listener class
    getGameListener().registerListener(new MyActionBarListener());
    getGameListener().registerListener(new MyLobbyListener());
  }

  @Override
  public String getName() {
    return "localhost";
  }

  @Override
  public String getConfigName() {
    return "localhost";
  }

  @Override
  public boolean handleServer(String host, int port) {
    return true;
  }
}
```

**Comment by 5zig** [comment] 2017-03-29 15:34
Did you try connecting to a server that is currently not supported by the 5zig mod?

**Comment by ghost** [comment] 2017-03-29 15:38
I don't know. I just tried it on mineplex. Everything else works though, e.g. the text replacements in chat.

**Comment by 5zig** [comment] 2017-03-29 16:11
Well, do you need your plugin to work on mineplex? If not, try it out on another server.

**Comment by ghost** [comment] 2017-03-29 16:20
I'd like it to work everywhere, and I just checked; it doesn't work anywhere.

Checked on mineplex, havoc, badlion, my localhost, a friends server. This covered BungeeCord, Spigot, Vanilla. Idk what Badlion is.

**Comment by 5zig** [comment] 2017-03-29 16:39
Could you please compare your plugin with the following source folder: [src.zip](https://github.com/5zig/The-5zig-API/files/879732/Plugin.src.zip)? It worked fine for me. Note that the module item will only be displayed if there actually was a recent action bar message and if the 5zig mod does not support the current server by itself.

**Comment by ghost** [comment] 2017-03-30 22:20
What do I need to do if it does support the server? And how can I get it to show all the time even if there has been no "recent' action bar message?

**Comment by ghost** [comment] 2017-03-30 22:24
And your source code didn't work for me, I saw your message 

> Note that the module item will only be displayed if there actually was a recent action bar message

and so tried running `/title @p actionbar {"text":"boi"}` a bunch of times. Still doesn't display the module item in 5zig.

Maven is creating this jarfile: 


[fivezigaddons-0.0.1.jar.zip](https://github.com/5zig/The-5zig-API/files/883957/fivezigaddons-0.0.1.jar.zip)

**Comment by 5zig** [comment] 2017-03-31 08:21
Your plugin worked totally fine for me. Just make sure you are actually connected to a real server when testing. The item will be always displayed if you don't return `null` in the `getValue` method.

But actually, I think there is a way easier way for you to display an action bar message, even without all the limitations I talked about earlier, if I reconsider your special case. (I really don't know why I didn't though about that earlier, to be honest, sorry). The way it would work is that you would register an event listener that gets called on every action message, no matter if you are connected to a server or not. You would need to reset the message when leaving the world by yourself, but that's it.
Heres the source folder of my test-project: 
[src.zip](https://github.com/5zig/The-5zig-API/files/884920/src.zip)
The only problem I noticed is that the action bar event does not get called when executed by the /title command, that will be fixed in an upcoming mod update. When using the raw chat command (what most server do use), the plugin does work though.
Hope that helps.

**Comment by ghost** [comment] 2017-03-31 19:42
Nice, that new plugin works just as expected.

Is there a way to show/hide (toggle) module items on keypresses?

**Comment by 5zig** [comment] 2017-03-31 20:56
Sure, just register a keybinding like in the basic1 example plugin.

**Comment by ghost** [comment] 2017-03-31 21:47
Awesome, everything is working perfectly now! Thank you so much for all your help, you've been incredible!

Damn I love your client so much, it's so nice as well for it to have a brilliant developer willing to spend time with noobs like me ;) Thanks so much

**Comment by 5zig** [comment] 2017-04-01 11:41
No problem, glad I could help. ;)

**Closed as completed by 5zig** 2017-04-01 11:41 UTC
